services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "2000:8080"
    #    env_file:
    #      - .env
    networks:
      - webnet

networks:
  webnet:
    driver: bridge